CREATE TABLE IF NOT EXISTS "inviteCodes" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"code"	TEXT NOT NULL UNIQUE,
	"creator"	INTEGER NOT NULL,
	"revoked" BOOLEAN NOT NULL,
	"used_by" TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("creator") REFERENCES "users"("ID")
)